version: "3"
services:
  web:
    image: ${REGISTRY}/dafarm-webapp:latest
    container_name: dafarm-webapp
    ports:
      - "0.0.0.0:3000:3000"
    volumes:
      - ${ENV_PATH}/.env:/app/.env
    environment:
      - REACT_APP_API_BASE_URL=http://122.47.78.214:8001/api/v1
